services:
  frontend:
    build:
      context: .
    ports:
      - "8081:80"
    environment:
      - BACKEND_URL=http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
